### ISSUE TITLE
SimpleAuth Blocked

### ISSUE THREAD

**Issue by 14Boss14** [EvolSoft/MSpawns#1]
I found a bug for the MSpawns plugin. The bug is:
If I have MSpawns enabled I cant anymore use /login on the SimpleAuth plugin. It sais permission denied. I hope this bug gets fixed.
Ps. Sorry for my english but english isn`t my language

**Comment by Flavius12** [comment]
This bug isn't related to MSpawns. It happens due to errors in SimpleAuth or PocketMine code

**Comment by 14Boss14** [comment]
But Login always works without MSpawn enabled.
--

Mittwoch, 11 März 2015, 06:38nachm. +01:00 von Flavius12 <notifications@github.com>:

**Comment by Flavius12** [comment]
There is no part of code which blocks login in MSpawns
