### ISSUE TITLE
.

### ISSUE THREAD

**Issue by TheDiamondYT1** [EvolSoft/MSpawns#11]
Hey @Flavius12_ can I have access to more repos so I can update and submit to [poggit](http://poggit.pmmp.io)? Thanks.

**Comment by TheDiamondYT1** [comment]
@Flavius12

**Comment by TheDiamondYT1** [comment]
Bump

**Comment by Flavius12** [comment]
Done

**Comment by TheDiamondYT1** [comment]
Thanks

**Comment by TheDiamondYT1** [comment]
@Flavius12 Hmm, it appears that i cant submit the plugin on poggit. Im guessing i need owner access on the organization. Can you go to https://poggit.pmmp.io/ci/EvolSoft/MSpawns/~ and sign in with github then click submit plugin

**Comment by Flavius12** [comment]
Now you should be able to submit plugins there
