### ISSUE TITLE
setalias work but if a player died internal server error

### ISSUE THREAD

**Issue by efor89** [EvolSoft/MSpawns#34]
hi

When I set an alias on my server spawn world and a player dies after the revives comes an internal server error. the player then also no longer comes to the server always direckt again an internal server error.
i need to delet the playerdata then he can join.

**Comment by Flavius12** [comment]
I'm sorry but PocketMine plugins are no longer maintained.

**Comment by efor89** [comment]
OK, too bad

**Comment by TungstenVn** [comment]
use this new pull request, this error is fixed
https://github.com/EvolSoft/MSpawns/pull/35
