### ISSUE TITLE
Features

### ISSUE THREAD

**Issue by vvzar** [EvolSoft/MSpawns#4]
Can You add respawn commands, spawn commands, variables like {player} {level} in it?
For commands need flag one command run per death.
Can You add /sethome /home. cmds?
Can You add tp {player} with request to {player} ? and /tph (/tp here) {player} with request.
Can You add permission nodes for this?

Thank You. All work like a charm!

**Comment by Flavius12** [comment]
There are already lots of plugins which do this. Look at EssentialsPE or at EssentialsTP. I think they are fully compatible with MSpawns
