### ISSUE TITLE
if you are dead

### ISSUE THREAD

**Issue by Driesboy** [EvolSoft/MSpawns#8]
you not teleported to spawn
you laggy into sky

**Comment by Flavius12** [comment]
This bug is related to your server software. Are you using PocketMine?

**Comment by Driesboy** [comment]
no
genisys it was the same on pocketmine

**Comment by Flavius12** [comment]
It's a server bug anyway

**Comment by Driesboy** [comment]
what i dont have it on other spawn plugins
only on this

**Comment by Driesboy** [comment]
IT DONT WORK FOR IM AND GENISYS, CLEARSKY AND POCKETMINE
